version: '3.1'
 # Changed to Joomla from Ghost due to failures
services:
  joomla:
    image: joomla
    restart: always
    links:
      - joomladb:mysql
    ports:
      - 8080:80
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: Nscc1234.
 
 # Removed mysql section to make as simple as possible
  joomladb:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Nscc1234.